version: "3.8"
 
services:
  postgres:
    image: postgres:16
    container_name: polls_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polls
    ports:
      - "5432:5432"
    volumes:
      - polls_pgdata:/var/lib/postgresql/data
 
volumes:
  polls_pgdata:
 